name: Build and Test

env:
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: 'Release'

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch: # Allow manual triggering
    inputs:
      run_code_analysis:
        description: 'Run code analysis'
        required: false
        default: false
        type: boolean
      run_windows_build:
        description: 'Run Windows build'
        required: false
        default: false
        type: boolean
      run_macos_build:
        description: 'Run macOS build'
        required: false
        default: false
        type: boolean

# Prevent concurrent builds of the same branch to save resources
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        configuration: [Release]
        include:
          # Add Windows build if requested via workflow_dispatch or if not a manual trigger
          - os: windows-latest
            configuration: Release
            run_build: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.run_windows_build == 'true' }}
          # Add macOS build if requested via workflow_dispatch or if not a manual trigger
          - os: macos-latest
            configuration: Release
            run_build: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.run_macos_build == 'true' }}
    
    # Skip this job if it's a Windows or macOS build that should be skipped
    if: |
      matrix.os == 'ubuntu-latest' || 
      (matrix.os == 'windows-latest' && matrix.run_build) || 
      (matrix.os == 'macos-latest' && matrix.run_build)
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Include Directory.Packages.props in the cache key since it contains all package versions
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}-${{ hashFiles('Directory.Build.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}-
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
    
    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal
      
    - name: Upload CfgVisualizer artifacts
      if: matrix.os == 'windows-latest' && matrix.run_build
      uses: actions/upload-artifact@v4
      with:
        name: cfg-visualizer
        path: |
          VibeDisasm.CfgVisualizer/bin/Release/**/*.dll
          VibeDisasm.CfgVisualizer/bin/Release/**/*.exe
          VibeDisasm.CfgVisualizer/bin/Release/**/*.pdb
          VibeDisasm.CfgVisualizer/bin/Release/**/*.json
        retention-days: 7

  code-coverage:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Include Directory.Packages.props in the cache key since it contains all package versions
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}-${{ hashFiles('Directory.Build.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}-
          ${{ runner.os }}-nuget-
    
    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    
    - name: Test with coverage
      run: |
        dotnet restore
        dotnet test --configuration ${{ env.CONFIGURATION }} --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    
    - name: Generate coverage report
      run: reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"./CoverageReport" -reporttypes:"HtmlInline_AzurePipelines;Cobertura;Badges"
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./CoverageReport
        retention-days: 14
        
  # Optional job for static code analysis
  code-analysis:
    # Only run when explicitly requested via workflow_dispatch input
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_code_analysis == 'true'
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Include Directory.Packages.props in the cache key since it contains all package versions
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}-${{ hashFiles('Directory.Build.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}-
          ${{ runner.os }}-nuget-
          
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
      
    - name: Run dotnet format
      run: dotnet format --verify-no-changes --verbosity diagnostic
